/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagestionbancaria;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sistemagestionbancaria.CuentaBancaria;
import sistemagestionbancaria.OperacionesUsuario;
import sistemagestionbancaria.SessionManager;

/**
 *
 * @author byvel
 */
public class CambioContrasena extends javax.swing.JFrame {

    /**
     * Creates new form CambioContrasena
     */
    public CambioContrasena() {
        initComponents();
        // Obtener la cuenta del usuario actual desde SessionManager
        CuentaBancaria cuenta = SessionManager.obtenerCuentaUsuarioActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtMontoRetiro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMensajeError = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPIN01 = new javax.swing.JPasswordField();
        txtPIN02 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        btnCambioPIN = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logito.png"))); // NOI18N

        txtMontoRetiro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtMontoRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoRetiroActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Monto a depositar:");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CAMBIO CONTRASEÑA");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 204)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logito.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cambio de PIN");

        lblMensajeError.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblMensajeError.setForeground(new java.awt.Color(255, 0, 0));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ingrese nuevamente la nueva contraseña:");

        txtPIN01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPIN02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 255));
        jLabel16.setText("Solo digitos del 0 al 9");

        btnCambioPIN.setBackground(new java.awt.Color(0, 0, 0));
        btnCambioPIN.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCambioPIN.setForeground(new java.awt.Color(255, 255, 255));
        btnCambioPIN.setText("CAMBIO CONTRASEÑA");
        btnCambioPIN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 204)));
        btnCambioPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioPINActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/star.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nueva contraseña:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtPIN01, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPIN02, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel16))
                            .addComponent(jLabel18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCambioPIN, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(lblMensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(2, 2, 2)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPIN01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPIN02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCambioPIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lblMensajeError)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoRetiroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    // Cambio de contraseña del usuario activo
    private void btnCambioPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioPINActionPerformed
        // Obtener la cuenta del usuario actual desde SessionManager
        CuentaBancaria cuenta = SessionManager.obtenerCuentaUsuarioActual();
        // Obtener la nueva contraseña ingresada por el usuario
        String nuevaContrasena = new String(txtPIN01.getPassword());
        String confirmacionContrasena = new String(txtPIN02.getPassword());

        // Validar si los PIN tienen cuatro dígitos exactamente
        if (nuevaContrasena.length() != 4 || confirmacionContrasena.length() != 4){
            JOptionPane.showMessageDialog(this, "El PIN debe contener 4 dígitos.", "PIN inválido", JOptionPane.ERROR_MESSAGE);
            // Limpiar los campos de PIN para volver a solicitarlos
            txtPIN02.setText("");
            txtPIN01.setText("");
        }
        //Verificar si los PIN consisten de digitos
        else if (!nuevaContrasena.matches("\\d{4}")||!confirmacionContrasena.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "El PIN debe contener solo dígitos.", "PIN inválido", JOptionPane.ERROR_MESSAGE);
            // Limpiar los campos de PIN para volver a solicitarlos
            txtPIN02.setText("");
            txtPIN01.setText("");
        }
        // Verificar si los PIN coinciden 
        else if (!nuevaContrasena.equals(confirmacionContrasena)) {
            JOptionPane.showMessageDialog(this, "Los PIN ingresados no coinciden. Por favor, intenta de nuevo.", "PIN inválido", JOptionPane.ERROR_MESSAGE);
            // Limpiar los campos de PIN para volver a solicitarlos
            txtPIN02.setText("");
            txtPIN01.setText("");
        } else {
            // Cambiar la contraseña de la cuenta actual
            cuenta.setPin(nuevaContrasena);

            // Actualizar la información en el archivo y en la lista de cuentas en SessionManager
            actualizarArchivoCuenta(cuenta);

            // Aquí podrías cerrar esta ventana y realizar otra acción, por ejemplo:
            OperacionesUsuario operaciones = new OperacionesUsuario();
            operaciones.show(); // Muestra la ventana operaciones de usuario
            dispose(); // Cierra la ventana actual
        }
    }//GEN-LAST:event_btnCambioPINActionPerformed
    // Método para actualizar el archivo de cuentas con la información actualizada
    private void actualizarArchivoCuenta(CuentaBancaria cuentaActualizada) {
        try (BufferedReader reader = new BufferedReader(new FileReader("cuentas.txt"))) {
            String linea;
            ArrayList<String> lineas = new ArrayList<>();

            while ((linea = reader.readLine()) != null) {
                if (linea.contains(cuentaActualizada.getUsuario())) {
                    linea = cuentaActualizada.aFormatoArchivo(); // Actualizar la línea con la cuenta actualizada
                }
                lineas.add(linea);
            }

            // Escribir todas las líneas actualizadas en el archivo
            try (PrintWriter writer = new PrintWriter(new FileWriter("cuentas.txt"))) {
                for (String updatedLine : lineas) {
                    writer.println(updatedLine);
                }
                // Actualizar la lista de cuentas en SessionManager después de modificar el archivo
                SessionManager.cargarCuentasDesdeArchivo();
            }
        } catch (IOException e) {
            e.printStackTrace(); // Manejo de excepciones al escribir en el archivo
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambioPIN;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JTextField txtMontoRetiro;
    private javax.swing.JPasswordField txtPIN01;
    private javax.swing.JPasswordField txtPIN02;
    // End of variables declaration//GEN-END:variables
}
