/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagestionbancaria;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 *
 * @author byvel
 */
public class Transferencia extends javax.swing.JFrame {

    /**
     * Creates new form Transferencia
     */
    public Transferencia() {
        initComponents();
        // Obtener la cuenta del usuario actual desde SessionManager
        CuentaBancaria cuenta = SessionManager.obtenerCuentaUsuarioActual();
        System.out.println("Usuario: "+cuenta.getUsuario());
        // Verificar si la cuenta se encontró y actualizar el JLabel con el balance
        if (cuenta != null) {
            double balance = cuenta.getBalance();
            lblBalanceUsuario.setText(String.valueOf(balance));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblBalanceUsuario = new javax.swing.JLabel();
        txtMontoTransferencia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCuentaDestino = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnTransferencia = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lblMensajeError = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logito.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/star.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logito.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Transferencia");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cuenta de origen:");

        lblBalanceUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblBalanceUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblBalanceUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BALANCE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(204, 255, 255))); // NOI18N

        txtMontoTransferencia.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtMontoTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoTransferenciaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Monto:");

        txtCuentaDestino.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaDestinoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cuenta de destino:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tipo de transferencia:");

        jComboBox2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directa", "Interbancia", "Item 3", "Item 4" }));

        btnTransferencia.setBackground(new java.awt.Color(0, 0, 0));
        btnTransferencia.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferencia.setText("TRANSFERENCIA");
        btnTransferencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 204)));
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/star.png"))); // NOI18N

        lblMensajeError.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblMensajeError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(lblBalanceUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(txtMontoTransferencia)
                            .addComponent(txtCuentaDestino)
                            .addComponent(lblMensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBalanceUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMontoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTransferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeError)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoTransferenciaActionPerformed

    private void txtCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaDestinoActionPerformed
    // Transferencia entre cuentas creadas en la misma aplicacion
    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed
        // Obtener las cuentas involucradas en la transferencia
        CuentaBancaria cuentaOrigen = SessionManager.obtenerCuentaUsuarioActual();
        String cuentaDestinoNumero = txtCuentaDestino.getText(); // Obtener el número de cuenta destino

        // Buscar las cuentas en la lista
        CuentaBancaria cuentaDestino = null;
        for (CuentaBancaria cuenta : SessionManager.getCuentas()) {
            if (cuenta.getUsuario().equals(cuentaDestinoNumero)) {
                cuentaDestino = cuenta;
                break;
            }
        }

        // Verificar que las cuentas existan
        if (cuentaOrigen != null && cuentaDestino != null) {
            // Obtener el monto a transferir
            double monto = Double.parseDouble(txtMontoTransferencia.getText());

            // Verificar si la cuenta origen tiene saldo suficiente
            if (cuentaOrigen.getBalance() >= monto) {
                // Realizar la transferencia
                cuentaOrigen.retirar(monto);
                double balanceActualizado = cuentaOrigen.getBalance();
                // Actualizar los saldos en el archivo cuentas.txt 
                // Actualizar la información en el archivo y en la lista de cuentas en SessionManager
                // Guardar cambios en el archivo
                cuentaOrigen.setBalance(balanceActualizado);
                actualizarArchivoCuenta(cuentaOrigen);
                cuentaDestino.depositar(monto);
                double balanceActualizado2 = cuentaDestino.getBalance();
                // Actualizar los saldos en el archivo cuentas.txt
                // Actualizar la información en el archivo y en la lista de cuentas en SessionManager
                // Guardar cambios en el archivo
                cuentaDestino.setBalance(balanceActualizado2);
                actualizarArchivoCuenta(cuentaDestino);

                // Actualizar la ventana actual con los nuevos saldos
                lblBalanceUsuario.setText(String.valueOf(cuentaOrigen.getBalance()));
                // Actualizar también el saldo de la cuenta destino si estás mostrando esa información
                
                // Registrar la transacción de cuenta origen
                RegistroTransacciones.guardarTransaccion(cuentaOrigen.getUsuario(), "Transferencia", monto);
                // Registrar la transacción de cuenta destino
                RegistroTransacciones.guardarTransaccion(cuentaDestino.getUsuario(), "Transferencia", monto);
            } else {
                // Mostrar un mensaje si la cuenta origen no tiene saldo suficiente
                lblMensajeError.setText("Saldo insuficiente para la transferencia");
            }
        } else {
            // Mostrar un mensaje si alguna de las cuentas no existe
            lblMensajeError.setText("Una o ambas cuentas no existen");
        }
        OperacionesUsuario operaciones = new OperacionesUsuario();
        operaciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTransferenciaActionPerformed
    // Método para actualizar el archivo de cuentas con la información actualizada
    private void actualizarArchivoCuenta(CuentaBancaria cuentaActualizada) {
        try (BufferedReader reader = new BufferedReader(new FileReader("cuentas.txt"))) {
            String linea;
            ArrayList<String> lineas = new ArrayList<>();

            while ((linea = reader.readLine()) != null) {
                if (linea.contains(cuentaActualizada.getUsuario())) {
                    linea = cuentaActualizada.aFormatoArchivo(); // Actualizar la línea con la cuenta actualizada
                }
                lineas.add(linea);
            }

            // Escribir todas las líneas actualizadas en el archivo
            try (PrintWriter writer = new PrintWriter(new FileWriter("cuentas.txt"))) {
                for (String updatedLine : lineas) {
                    writer.println(updatedLine);
                }
                
                // Actualizar la lista de cuentas en SessionManager después de modificar el archivo
                SessionManager.cargarCuentasDesdeArchivo();
            }
        } catch (IOException e) {
            e.printStackTrace(); // Manejo de excepciones al escribir en el archivo
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalanceUsuario;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtMontoTransferencia;
    // End of variables declaration//GEN-END:variables
}
